# -*- coding: utf-8 -*-
"""03_face_morph_p1_LoRA_inference_evaluate.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1krFx8SZBsJHc-xIHJF0ElInXp4UhLsaj

改成用CLIP Score（ViT-L/14）、FID、LPIPS、DINO、ArcFace Identity Score、Edge IoU這六種方式測試

# 1. 安裝套件
"""

!pip install -q open_clip_torch lpips pytorch-fid transformers insightface onnxruntime
!pip install -q opencv-python-headless Pillow

"""# 2. Import + Drive mount + 路徑設定

LORA_WEIGHTS 對應你的人臉 LoRA（lora_output_test），TEST_INDICES 預設 10 張(改成50了)，之後可改成 range(0, 50)。
"""

import os, cv2, json, torch
import numpy as np
from PIL import Image
import matplotlib.pyplot as plt
import pandas as pd
from google.colab import drive

drive.mount('/content/drive')

# ====== 修改這裡對應你的路徑 ======
DRIVE_BASE      = "/content/drive/MyDrive/++DL/04_project_face"
LORA_WEIGHTS    = f"{DRIVE_BASE}/lora_output_morph_test_p1"   # 新參數 LoRA（方向 B 人臉）
DATA_DIR        = f"{DRIVE_BASE}/training_data_morph"        # 人臉資料根目錄
SKETCH_DIR      = f"{DATA_DIR}/conditioning_images"      # Canny sketch
PHOTO_DIR       = f"{DATA_DIR}/images"                   # ground truth photo
OUTPUT_DIR      = f"{DRIVE_BASE}/eval_6metrics_morph_p1"
TEST_INDICES    = list(range(0,  50))                     # 評估哪幾張（可改 range(0,50)）
PROMPT          = "a person, photorealistic, high quality, detailed skin"
NEG_PROMPT      = "low quality, blurry, cartoon, anime, deformed, ugly"
SEED            = 42

os.makedirs(OUTPUT_DIR, exist_ok=True)
device = "cuda" if torch.cuda.is_available() else "cpu"
print("Device:", device)

"""# 3. 載入 Pipeline（Baseline + LoRA）

一樣會自動斷掉，不怕，接著執行上一個儲存格(路徑設定)、下一個儲存格(載入pipeline)。
"""

!pip install torchao==0.16.0 -q
import os; os.kill(os.getpid(), 9)  # 重啟 runtime

from diffusers import ControlNetModel, StableDiffusionControlNetPipeline
from peft import PeftModel

# --- Baseline ---
controlnet = ControlNetModel.from_pretrained(
    "lllyasviel/sd-controlnet-scribble",
    torch_dtype=torch.float16
)
pipe_baseline = StableDiffusionControlNetPipeline.from_pretrained(
    "runwayml/stable-diffusion-v1-5",
    controlnet=controlnet,
    torch_dtype=torch.float16,
    safety_checker=None
).to(device)
pipe_baseline.enable_attention_slicing()
print("Baseline pipeline ready")

# --- LoRA ---
pipe_lora = StableDiffusionControlNetPipeline.from_pretrained(
    "runwayml/stable-diffusion-v1-5",
    controlnet=controlnet,
    torch_dtype=torch.float16,
    safety_checker=None
).to(device)
pipe_lora.enable_attention_slicing()
pipe_lora.unet = PeftModel.from_pretrained(
    pipe_lora.unet,
    LORA_WEIGHTS
).to(device)
print("LoRA pipeline ready")

"""# 4. 定義六個 metric 函式

定義六個 metric 函式。每個函式上面有注釋說明衡量什麼、來源論文是哪篇
"""

import open_clip
import lpips
from transformers import AutoModel, AutoProcessor

# ------------------------------------------------------------------
# Metric 1：CLIP Score（ViT-L/14）
# ------------------------------------------------------------------
clip_model, _, clip_preprocess = open_clip.create_model_and_transforms(
    'ViT-L-14', pretrained='openai'
)
clip_model = clip_model.to(device).eval()
clip_tokenizer = open_clip.get_tokenizer('ViT-L-14')

def compute_clip_score(image: Image.Image, prompt: str) -> float:
    """
    語意一致性：生成圖 embedding 與 text embedding 的 cosine similarity。
    來源：Radford et al., 2021, "Learning Transferable Visual Models From Natural Language Supervision" (CLIP, ICML 2021)
    """
    img_t = clip_preprocess(image).unsqueeze(0).to(device)
    txt_t = clip_tokenizer([prompt]).to(device)
    with torch.no_grad():
        img_feat = clip_model.encode_image(img_t)
        txt_feat = clip_model.encode_text(txt_t)
        img_feat /= img_feat.norm(dim=-1, keepdim=True)
        txt_feat /= txt_feat.norm(dim=-1, keepdim=True)
    return (img_feat * txt_feat).sum().item()


# ------------------------------------------------------------------
# Metric 2：LPIPS（感知相似度，越低越好）
# ------------------------------------------------------------------
lpips_fn = lpips.LPIPS(net='vgg').to(device)

def compute_lpips(generated: Image.Image, ground_truth: Image.Image) -> float:
    """
    感知相似度：用 VGG 中間層 feature 計算，比 pixel-wise L2 更接近人眼。
    值域 0~1，越低越好。
    來源：Zhang et al., 2018, "The Unreasonable Effectiveness of Deep Features as a Perceptual Metric" (CVPR 2018)
    """
    def to_tensor(img):
        t = torch.from_numpy(np.array(img.resize((512, 512))).astype(np.float32) / 127.5 - 1.0)
        return t.permute(2, 0, 1).unsqueeze(0).to(device)
    with torch.no_grad():
        score = lpips_fn(to_tensor(generated), to_tensor(ground_truth))
    return score.item()


# ------------------------------------------------------------------
# Metric 3：SSIM（結構相似度，越高越好）
# ------------------------------------------------------------------
from skimage.metrics import structural_similarity as skimage_ssim

def compute_ssim(generated: Image.Image, ground_truth: Image.Image) -> float:
    """
    結構相似度：比較亮度、對比、結構三個維度，值域 0~1，越高越好。
    常與 LPIPS 搭配使用互補（SSIM 對模糊敏感，LPIPS 對感知細節敏感）。
    來源：Wang et al., 2004, "Image Quality Assessment: From Error Visibility to Structural Similarity" (IEEE TIP)
    """
    gen_arr = np.array(generated.resize((512, 512)))
    gt_arr  = np.array(ground_truth.resize((512, 512)))
    return skimage_ssim(gen_arr, gt_arr, channel_axis=2, data_range=255)


# ------------------------------------------------------------------
# Metric 4：DINOv2 Cosine Similarity（越高越好）
# ------------------------------------------------------------------
dino_processor = AutoProcessor.from_pretrained("facebook/dinov2-base")
dino_model = AutoModel.from_pretrained("facebook/dinov2-base").to(device).eval()

def compute_dino_similarity(generated: Image.Image, ground_truth: Image.Image) -> float:
    """
    視覺語意相似度：用 DINOv2 self-supervised ViT 提取 [CLS] token embedding，
    計算 cosine similarity。不受 text-image pairing bias 影響，對真實感判斷比 CLIP 更準。
    值域 -1~1，越高越好。
    來源：Oquab et al., 2023, "DINOv2: Learning Robust Visual Features without Supervision" (TMLR 2024)
    """
    def get_embedding(img):
        inputs = dino_processor(images=img, return_tensors="pt").to(device)
        with torch.no_grad():
            outputs = dino_model(**inputs)
        return outputs.last_hidden_state[:, 0, :]  # [CLS] token

    feat_gen = get_embedding(generated)
    feat_gt  = get_embedding(ground_truth)
    feat_gen = feat_gen / feat_gen.norm(dim=-1, keepdim=True)
    feat_gt  = feat_gt  / feat_gt.norm(dim=-1, keepdim=True)
    return (feat_gen * feat_gt).sum().item()


# ------------------------------------------------------------------
# Metric 5：ArcFace Identity Score（人臉 identity 相似度，越高越好）
# ------------------------------------------------------------------
import insightface
from insightface.app import FaceAnalysis

arcface_app = FaceAnalysis(name="buffalo_l", providers=["CUDAExecutionProvider", "CPUExecutionProvider"])
arcface_app.prepare(ctx_id=0, det_size=(512, 512))

def compute_arcface_score(generated: Image.Image, ground_truth: Image.Image) -> float:
    """
    人臉 identity 相似度：用 ArcFace (buffalo_l) 提取 512-dim face embedding，
    計算 cosine similarity。專門量「臉長得多像」，是人臉生成任務的核心指標。
    值域 -1~1，越高越好（>0.3 通常視為同一人）。
    來源：Deng et al., 2019, "ArcFace: Additive Angular Margin Loss for Deep Face Recognition" (CVPR 2019)
    注意：若偵測不到人臉（如 sketch 太抽象），回傳 None。
    """
    def get_face_embedding(img: Image.Image):
        img_bgr = cv2.cvtColor(np.array(img.resize((512, 512))), cv2.COLOR_RGB2BGR)
        faces = arcface_app.get(img_bgr)
        if len(faces) == 0:
            return None
        return faces[0].normed_embedding  # 已 L2-normalize

    emb_gen = get_face_embedding(generated)
    emb_gt  = get_face_embedding(ground_truth)

    if emb_gen is None or emb_gt is None:
        return None   # 偵測失敗，跳過這張
    return float(np.dot(emb_gen, emb_gt))


# ------------------------------------------------------------------
# Metric 6：Edge IoU（結構控制忠實度，越高越好）
# ------------------------------------------------------------------
def compute_edge_iou(generated: Image.Image, sketch: Image.Image) -> float:
    """
    邊緣 IoU：對生成圖跑 Canny，與輸入 sketch 的邊緣做 IoU，
    衡量「生成結果有沒有忠實跟著草圖的輪廓」。
    值域 0~1，越高越好。
    """
    gen_gray  = cv2.cvtColor(np.array(generated.resize((512, 512))), cv2.COLOR_RGB2GRAY)
    gen_edges = cv2.Canny(gen_gray, 50, 150)

    sk_gray = cv2.cvtColor(np.array(sketch.resize((512, 512))), cv2.COLOR_RGB2GRAY)
    _, sk_edges = cv2.threshold(sk_gray, 128, 255, cv2.THRESH_BINARY_INV)

    intersection = np.logical_and(gen_edges > 0, sk_edges > 0).sum()
    union        = np.logical_or(gen_edges > 0, sk_edges > 0).sum()
    return float(intersection / (union + 1e-6))


print("所有 metric 函式載入完成")

"""# 5. 批次推論 + 計算六指標

批次推論並計算六指標，存成 CSV。ArcFace 偵測失敗（sketch 太抽象、生成圖沒有正臉）會回傳 None

跑 50 筆大概二十分鐘。
"""

results = []

for i in TEST_INDICES:
    sketch   = Image.open(f"{SKETCH_DIR}/{i:04d}.png").convert("RGB")
    gt_photo = Image.open(f"{PHOTO_DIR}/{i:04d}.png").convert("RGB")
    gen_kwargs = dict(
        prompt            = PROMPT,
        negative_prompt   = NEG_PROMPT,
        image             = sketch,
        num_inference_steps = 30,
        guidance_scale    = 7.5,
        generator         = torch.Generator(device).manual_seed(SEED)
    )

    result_baseline = pipe_baseline(**gen_kwargs).images[0]
    result_lora     = pipe_lora(**gen_kwargs).images[0]

    # ---------- 計算六指標 ----------
    row = {"idx": i}

    # 1. CLIP Score (ViT-L/14)
    row["clip_base"] = compute_clip_score(result_baseline, PROMPT)
    row["clip_lora"] = compute_clip_score(result_lora,     PROMPT)

    # 2. LPIPS（vs ground truth，越低越好）
    row["lpips_base"] = compute_lpips(result_baseline, gt_photo)
    row["lpips_lora"] = compute_lpips(result_lora,     gt_photo)

    # 3. SSIM（vs ground truth，越高越好）
    row["ssim_base"] = compute_ssim(result_baseline, gt_photo)
    row["ssim_lora"] = compute_ssim(result_lora,     gt_photo)

    # 4. DINOv2 Similarity（vs ground truth，越高越好）
    row["dino_base"] = compute_dino_similarity(result_baseline, gt_photo)
    row["dino_lora"] = compute_dino_similarity(result_lora,     gt_photo)

    # 5. ArcFace Identity Score（vs ground truth，越高越好）
    row["arcface_base"] = compute_arcface_score(result_baseline, gt_photo)
    row["arcface_lora"] = compute_arcface_score(result_lora,     gt_photo)

    # 6. Edge IoU（vs sketch，越高越好）
    row["edge_base"] = compute_edge_iou(result_baseline, sketch)
    row["edge_lora"] = compute_edge_iou(result_lora,     sketch)

    results.append(row)
    print(f"[{i:04d}] CLIP: {row['clip_base']:.4f}/{row['clip_lora']:.4f} | "
          f"LPIPS: {row['lpips_base']:.4f}/{row['lpips_lora']:.4f} | "
          f"DINOv2: {row['dino_base']:.4f}/{row['dino_lora']:.4f} | "
          f"ArcFace: {row['arcface_base']}/{row['arcface_lora']} | "
          f"Edge: {row['edge_base']:.4f}/{row['edge_lora']:.4f}")

df = pd.DataFrame(results)
df.to_csv(f"{OUTPUT_DIR}/eval_6metrics.csv", index=False)
print(f"\\n結果已存至 {OUTPUT_DIR}/eval_6metrics.csv")

"""# 6. 印出彙整表格

==============================================================

Metric                   Baseline       LoRA          Δ

--------------------------------------------------------------

CLIP Score ↑               0.2097     0.1731   -0.0367 ↓

LPIPS ↓                    0.7274     0.6846   -0.0428 ↓

SSIM ↑                     0.1655     0.2379   +0.0725 ↑

DINOv2 Sim ↑               0.1268     0.2868   +0.1600 ↑

ArcFace ID Score ↑         0.0270     0.0113   -0.0157 ↓

Edge IoU ↑                 0.1022     0.1022   -0.0001 ↓

==============================================================

（樣本數：50 張；ArcFace None 數量：9 張）
"""

metrics = {
    "CLIP Score ↑":         ("clip_base",    "clip_lora"),
    "LPIPS ↓":              ("lpips_base",   "lpips_lora"),
    "SSIM ↑":               ("ssim_base",    "ssim_lora"),
    "DINOv2 Sim ↑":         ("dino_base",    "dino_lora"),
    "ArcFace ID Score ↑":   ("arcface_base",  "arcface_lora"),
    "Edge IoU ↑":           ("edge_base",    "edge_lora"),
}

# ArcFace 可能有 None（偵測失敗），計算平均時過濾掉
df_clean = df.copy()
for col in ["arcface_base", "arcface_lora"]:
    df_clean[col] = pd.to_numeric(df_clean[col], errors='coerce')

print("=" * 62)
print(f"{'Metric':<22} {'Baseline':>10} {'LoRA':>10} {'Δ':>10}")
print("-" * 62)

for label, (col_b, col_l) in metrics.items():
    mean_b = df_clean[col_b].mean()
    mean_l = df_clean[col_l].mean()
    delta  = mean_l - mean_b
    arrow  = "↑" if delta > 0 else "↓"
    print(f"{label:<22} {mean_b:>10.4f} {mean_l:>10.4f} {delta:>+9.4f} {arrow}")

print("=" * 62)
print(f"（樣本數：{len(df)} 張；ArcFace None 數量：{df_clean['arcface_lora'].isna().sum()} 張）")

"""# 7. FID（需要額外存圖，最後跑）

FID 單獨跑，因為需要先把圖存成資料夾再算。建議樣本數 ≥ 50 才有統計意義，可以在這個 Cell 把 TEST_INDICES 擴大成 50 張。

FID:  288.87316041283333

FID LoRA    :  225.6705847165703
"""

# FID 需要兩個資料夾各至少 50 張才統計上有意義，先批量存圖再算
import shutil
from tqdm import tqdm

dir_real      = f"{OUTPUT_DIR}/fid_real"
dir_baseline  = f"{OUTPUT_DIR}/fid_baseline"
dir_lora      = f"{OUTPUT_DIR}/fid_lora"
for d in [dir_real, dir_baseline, dir_lora]:
    os.makedirs(d, exist_ok=True)

# 如果 TEST_INDICES 只有 10 張，FID 結果僅供參考（不夠穩定）
# 建議把 TEST_INDICES 改成 range(0, 50) 再跑這個 Cell
for i in tqdm(TEST_INDICES, desc="Saving images for FID"):
    sketch   = Image.open(f"{SKETCH_DIR}/{i:04d}.png").convert("RGB")
    gt_photo = Image.open(f"{PHOTO_DIR}/{i:04d}.png").convert("RGB")
    gen_kwargs = dict(
        prompt=PROMPT, negative_prompt=NEG_PROMPT, image=sketch,
        num_inference_steps=30, guidance_scale=7.5,
        generator=torch.Generator(device).manual_seed(SEED)
    )

    result_baseline = pipe_baseline(**gen_kwargs).images[0]
    result_lora     = pipe_lora(**gen_kwargs).images[0]

    gt_photo.save(f"{dir_real}/{i:04d}.png")
    result_baseline.save(f"{dir_baseline}/{i:04d}.png")
    result_lora.save(f"{dir_lora}/{i:04d}.png")

# 計算 FID
import subprocess
res_b = subprocess.run(
    ["python", "-m", "pytorch_fid", dir_real, dir_baseline, "--device", "cuda"],
    capture_output=True, text=True
)
res_l = subprocess.run(
    ["python", "-m", "pytorch_fid", dir_real, dir_lora, "--device", "cuda"],
    capture_output=True, text=True
)

print("FID Baseline:", res_b.stdout.strip())
print("FID LoRA    :", res_l.stdout.strip())
# FID 越低越好；差距 >5 算有意義，<2 可能在雜訊範圍內

"""# 8. 視覺化 evaluation grid"""

N = min(10, len(TEST_INDICES))
fig, axes = plt.subplots(N, 4, figsize=(20, 5 * N))

for row_i, i in enumerate(TEST_INDICES[:N]):
    sketch   = Image.open(f"{SKETCH_DIR}/{i:04d}.png").convert("RGB")
    gt_photo = Image.open(f"{PHOTO_DIR}/{i:04d}.png").convert("RGB")
    sketch_gen = sketch  # 用於推論

    gen_kwargs = dict(
        prompt=PROMPT, negative_prompt=NEG_PROMPT, image=sketch_gen,
        num_inference_steps=30, guidance_scale=7.5,
        generator=torch.Generator(device).manual_seed(SEED)
    )
    result_baseline = pipe_baseline(**gen_kwargs).images[0]
    result_lora     = pipe_lora(**gen_kwargs).images[0]

    r = df[df["idx"] == i].iloc[0]

    axes[row_i][0].imshow(sketch);          axes[row_i][0].set_title(f"[{i}] Input Sketch");       axes[row_i][0].axis("off")
    axes[row_i][1].imshow(gt_photo);        axes[row_i][1].set_title(f"[{i}] Ground Truth");        axes[row_i][1].axis("off")
    axes[row_i][2].imshow(result_baseline); axes[row_i][2].set_title(
        f"[{i}] Baseline\nCLIP={r['clip_base']:.3f} LPIPS={r['lpips_base']:.3f}\n"
        f"DINO={r['dino_base']:.3f} Edge={r['edge_base']:.3f}"
    ); axes[row_i][2].axis("off")
    axes[row_i][3].imshow(result_lora);     axes[row_i][3].set_title(
        f"[{i}] LoRA\nCLIP={r['clip_lora']:.3f} LPIPS={r['lpips_lora']:.3f}\n"
        f"DINO={r['dino_lora']:.3f} Edge={r['edge_lora']:.3f}"
    ); axes[row_i][3].axis("off")

plt.suptitle("Face LoRA Evaluation: 6-Metric Grid", fontsize=16, y=1.002)
plt.tight_layout()
save_path = f"{OUTPUT_DIR}/evaluation_grid_6metrics.png"
plt.savefig(save_path, dpi=120, bbox_inches="tight")
plt.show()
print(f"Grid 已存至 {save_path}")