# -*- coding: utf-8 -*-
"""04_real_test.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15yUQGVpewNbajh4Piw_ZvuooRWFrrEeG

# Sketch Evaluation: Real-world sketches vs 3 LoRA models

Metrics: CLIP Score, FID, Edge IoU

# 1. 安裝套件
"""

!pip install -q open_clip_torch lpips clean-fid controlnet-aux
!pip install -q diffusers transformers accelerate peft
!pip install -q torchao==0.16.0

import os; os.kill(os.getpid(), 9)  # 重啟 runtime

"""# 2. Import"""

import os, json, torch, cv2, shutil
import numpy as np
import pandas as pd
from PIL import Image
from tqdm import tqdm
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec

from google.colab import drive, files
from diffusers import StableDiffusionControlNetPipeline, ControlNetModel
from peft import PeftModel
import open_clip
from cleanfid import fid as clean_fid

drive.mount('/content/drive')
print("Import 完成")

"""# 3. 路徑設定"""

DRIVE_BASE   = "/content/drive/MyDrive/++DL/04_project_face"

LORA_CANNY   = f"{DRIVE_BASE}/lora_output_test_p1"
LORA_MORPH   = f"{DRIVE_BASE}/lora_output_morph_test_p1"   # 請確認資料夾名稱
LORA_HED     = f"{DRIVE_BASE}/lora_output_HED_test_p1"     # 請確認資料夾名稱

SKETCH_DIR   = "/content/user_sketches"            # 上傳草圖存放位置
OUTPUT_DIR   = "/content/eval_realworld"           # 結果輸出位置
CSV_PATH     = f"{OUTPUT_DIR}/results.csv"

PROMPT       = "a person, photorealistic, high quality, detailed skin"
NEG_PROMPT   = "low quality, blurry, cartoon, anime, deformed, ugly"
SEED         = 42
NUM_STEPS    = 30
GUIDANCE     = 7.5

os.makedirs(SKETCH_DIR, exist_ok=True)
os.makedirs(OUTPUT_DIR, exist_ok=True)
for name in ["baseline", "canny", "morph", "hed"]:
    os.makedirs(f"{OUTPUT_DIR}/{name}", exist_ok=True)

print("路徑設定完成")

"""# 4. 上傳草圖"""

print("請上傳草圖（支援 jpg / png，可多選）")
uploaded = files.upload()

for fname, data in uploaded.items():
    dest = os.path.join(SKETCH_DIR, fname)
    with open(dest, "wb") as f:
        f.write(data)

sketch_paths = sorted([
    os.path.join(SKETCH_DIR, f)
    for f in os.listdir(SKETCH_DIR)
    if f.lower().endswith((".jpg", ".jpeg", ".png"))
])

print(f"共上傳 {len(sketch_paths)} 張草圖")
print("草圖列表：", [os.path.basename(p) for p in sketch_paths])

# 預覽前 5 張
fig, axes = plt.subplots(1, min(5, len(sketch_paths)), figsize=(15, 3))
if len(sketch_paths) == 1:
    axes = [axes]
for ax, p in zip(axes, sketch_paths[:5]):
    ax.imshow(Image.open(p).convert("RGB"))
    ax.set_title(os.path.basename(p)[:12])
    ax.axis("off")
plt.suptitle("Uploaded Sketches (first 5)")
plt.tight_layout()
plt.show()

"""# 5. 載入模型"""

def load_pipeline(lora_path=None):
    controlnet = ControlNetModel.from_pretrained(
        "lllyasviel/sd-controlnet-scribble",
        torch_dtype=torch.float16
    )
    pipe = StableDiffusionControlNetPipeline.from_pretrained(
        "runwayml/stable-diffusion-v1-5",
        controlnet=controlnet,
        torch_dtype=torch.float16,
        safety_checker=None
    ).to("cuda")
    pipe.enable_attention_slicing()

    if lora_path is not None:
        pipe.unet = PeftModel.from_pretrained(
            pipe.unet, lora_path
        ).to("cuda")
        print(f"  LoRA loaded: {lora_path}")
    else:
        print("  Baseline (no LoRA)")
    return pipe

print("Loading baseline...")
pipe_baseline = load_pipeline(None)
print("Loading Canny LoRA...")
pipe_canny    = load_pipeline(LORA_CANNY)
print("Loading Morph LoRA...")
pipe_morph    = load_pipeline(LORA_MORPH)
print("Loading HED LoRA...")
pipe_hed      = load_pipeline(LORA_HED)

PIPELINES = {
    "baseline": pipe_baseline,
    "canny":    pipe_canny,
    "morph":    pipe_morph,
    "hed":      pipe_hed,
}
print("\n全部模型載入完成")

"""# 6. 定義 Metric 函式"""

# --- CLIP Score ---
clip_model, _, clip_preprocess = open_clip.create_model_and_transforms(
    'ViT-L-14', pretrained='openai'
)
clip_model = clip_model.to("cuda").eval()
clip_tokenizer = open_clip.get_tokenizer('ViT-L-14')

def compute_clip_score(image: Image.Image, prompt: str) -> float:
    img_t = clip_preprocess(image).unsqueeze(0).to("cuda")
    txt_t = clip_tokenizer([prompt]).to("cuda")
    with torch.no_grad():
        i = clip_model.encode_image(img_t)
        i /= i.norm(dim=-1, keepdim=True)
        t = clip_model.encode_text(txt_t)
        t /= t.norm(dim=-1, keepdim=True)
    return (i * t).sum().item()

# --- Edge IoU ---
def compute_edge_iou(generated: Image.Image, sketch: Image.Image) -> float:
    gen_np  = np.array(generated.convert("RGB").resize((512, 512)))
    sk_np   = np.array(sketch.convert("RGB").resize((512, 512)))

    gen_gray  = cv2.cvtColor(gen_np, cv2.COLOR_RGB2GRAY)
    gen_edges = cv2.Canny(gen_gray, 50, 150)

    sk_gray = cv2.cvtColor(sk_np, cv2.COLOR_RGB2GRAY)
    _, sk_edges = cv2.threshold(sk_gray, 128, 255, cv2.THRESH_BINARY_INV)

    intersection = np.logical_and(gen_edges > 0, sk_edges > 0).sum()
    union        = np.logical_or(gen_edges > 0, sk_edges > 0).sum()
    return float(intersection / (union + 1e-6))

print("Metric 函式定義完成")

"""# 7. 批次推論 + 計算指標"""

generator = torch.Generator("cuda").manual_seed(SEED)
records   = []

for sketch_path in tqdm(sketch_paths, desc="Sketches"):
    fname  = os.path.basename(sketch_path)
    sketch = Image.open(sketch_path).convert("RGB").resize((512, 512))

    row = {"filename": fname}

    for model_name, pipe in PIPELINES.items():
        gen = pipe(
            prompt           = PROMPT,
            negative_prompt  = NEG_PROMPT,
            image            = sketch,
            num_inference_steps = NUM_STEPS,
            guidance_scale   = GUIDANCE,
            generator        = generator,
        ).images[0]

        # 存生成圖
        save_path = f"{OUTPUT_DIR}/{model_name}/{fname}"
        gen.save(save_path)

        # 計算指標
        clip  = compute_clip_score(gen, PROMPT)
        eiou  = compute_edge_iou(gen, sketch)

        row[f"{model_name}_clip"]     = round(clip, 4)
        row[f"{model_name}_edge_iou"] = round(eiou, 4)

    records.append(row)

df = pd.DataFrame(records)
df.to_csv(CSV_PATH, index=False)
print(f"\n推論完成，結果存至 {CSV_PATH}")
print(df.to_string(index=False))

"""# 8. 計算 FID（每個模型 vs 整批生成圖）

FID 需要兩個資料夾：「參考真實圖」和「生成圖」
 因為是 real-world sketch，沒有 ground truth，
 所以用 clean-fid 的 "stats from folder" 模式：
 以 baseline 生成圖為參考分佈，比較各 LoRA 的生成分佈
（相對比較，不是絕對值）
"""

REFERENCE_DIR = f"{OUTPUT_DIR}/baseline"  # 以 baseline 為參考

fid_scores = {}
for model_name in ["canny", "morph", "hed"]:
    score = clean_fid.compute_fid(
        REFERENCE_DIR,
        f"{OUTPUT_DIR}/{model_name}",
        mode="clean",
        num_workers=0,
        batch_size=8,
    )
    fid_scores[model_name] = round(score, 4)
    print(f"FID  {model_name} vs baseline: {score:.4f}")

fid_df = pd.DataFrame([fid_scores], index=["FID vs baseline"])
print("\n")
print(fid_df.to_string())

"""# 9. 彙整表格

============================================================

 CLIP Score (↑)  Edge IoU (↑)  FID vs baseline (↓)

baseline          0.2008        0.0578               0.0000

canny             0.1727        0.0450             190.9469

morph             0.1871        0.0498             233.0690

hed               0.1867        0.0508             164.7383

============================================================
"""

models = ["baseline", "canny", "morph", "hed"]

summary = {}
for m in models:
    summary[m] = {
        "CLIP Score (↑)": round(df[f"{m}_clip"].mean(), 4),
        "Edge IoU (↑)":   round(df[f"{m}_edge_iou"].mean(), 4),
    }

summary_df = pd.DataFrame(summary).T

# 加入 FID（baseline 本身為參考，所以填 0.0 作為基準）
summary_df["FID vs baseline (↓)"] = [
    0.0,
    fid_scores.get("canny", float("nan")),
    fid_scores.get("morph", float("nan")),
    fid_scores.get("hed",   float("nan")),
]

print("=" * 60)
print("Summary Table")
print("=" * 60)
print(summary_df.to_string())
print("=" * 60)

# 存成 CSV
summary_df.to_csv(f"{OUTPUT_DIR}/summary.csv")
print(f"Summary 存至 {OUTPUT_DIR}/summary.csv")

"""# 10. 視覺化比較圖"""

# 每張 sketch 生成一張並排圖：Sketch | Baseline | Canny | Morph | HED

VIS_DIR = f"{OUTPUT_DIR}/comparison_grids"
os.makedirs(VIS_DIR, exist_ok=True)

for sketch_path in sketch_paths:
    fname  = os.path.basename(sketch_path)
    sketch = Image.open(sketch_path).convert("RGB").resize((512, 512))

    imgs   = [sketch] + [
        Image.open(f"{OUTPUT_DIR}/{m}/{fname}").convert("RGB")
        for m in models
    ]
    labels = ["Input Sketch", "Baseline", "LoRA (Canny)", "LoRA (Morph)", "LoRA (HED)"]

    fig, axes = plt.subplots(1, 5, figsize=(20, 4))
    for ax, img, label in zip(axes, imgs, labels):
        ax.imshow(img)
        ax.set_title(label, fontsize=10)
        ax.axis("off")

    # 加上各指標數值
    row = df[df["filename"] == fname].iloc[0]
    metric_text = "  ".join([
        f"{m}: CLIP={row[f'{m}_clip']:.3f} IoU={row[f'{m}_edge_iou']:.3f}"
        for m in models
    ])
    fig.suptitle(f"{fname}\n{metric_text}", fontsize=8, y=1.02)

    plt.tight_layout()
    save_path = f"{VIS_DIR}/{fname.replace('.', '_')}_grid.png"
    plt.savefig(save_path, bbox_inches="tight", dpi=120)
    plt.show()
    plt.close()

print(f"比較圖存至 {VIS_DIR}/")